daxpy – slsqp
daxpy Subroutine
33 statements
Source File
public subroutine daxpy(n, da, dx, incx, dy, incy)
constant times a vector plus a vector. uses unrolled loops for increments equal to one.
Author
jack dongarra, linpack, 3/11/78.
Arguments
Type Intent Optional Attributes Name
integer :: n
real(kind=wp) :: da
real(kind=wp) :: dx(*)
integer :: incx
real(kind=wp) :: dy(*)
integer :: incy
Called By
Source Code
daxpy
Source Code
    subroutine daxpy(n,da,dx,incx,dy,incy)
    implicit none
    real(wp) :: dx(*) , dy(*) , da
    integer :: i , incx , incy , ix , iy , m , mp1 , n
    if ( n<=0 ) return
    if ( abs(da)<=zero ) return
    if ( incx==1 .and. incy==1 ) then
        ! code for both increments equal to 1
        ! clean-up loop
        m = mod(n,4)
        if ( m/=0 ) then
            do i = 1 , m
                dy(i) = dy(i) + da*dx(i)
            end do
            if ( n<4 ) return
        end if
        mp1 = m + 1
        do i = mp1 , n , 4
            dy(i) = dy(i) + da*dx(i)
            dy(i+1) = dy(i+1) + da*dx(i+1)
            dy(i+2) = dy(i+2) + da*dx(i+2)
            dy(i+3) = dy(i+3) + da*dx(i+3)
        end do
    else
        ! code for unequal increments or equal increments
        ! not equal to 1
        ix = 1
        iy = 1
        if ( incx<0 ) ix = (-n+1)*incx + 1
        if ( incy<0 ) iy = (-n+1)*incy + 1
        do i = 1 , n
            dy(iy) = dy(iy) + da*dx(ix)
            ix = ix + incx
            iy = iy + incy
        end do
    end if
    end subroutine daxpy
All Procedures
check_convergence daxpy dcopy ddot destroy_linmin_data destroy_slsqp destroy_slsqpb_data diff dnrm2 dscal dummy_grad enforce_bounds func g1 grad h12 hfti initialize_slsqp ldl ldp linmin lsei lsi lsq mode_to_status_message nnls report_iteration report_iteration report_iteration report_iteration report_iteration report_message rosenbrock_func rosenbrock_func rosenbrock_func rosenbrock_grad rosenbrock_grad slsqp slsqp_wrapper slsqpb stop_iterations test_func test_grad
Call graph
slsqpb calls daxpy, lsq
ldp calls daxpy
lsi calls daxpy, ldp
slsqp calls slsqpb
slsqp_wrapper calls slsqp
lsei calls lsi
lsq calls lsei