ddot – slsqp
ddot Function
36 statements
Source File
public function ddot(n, dx, incx, dy, incy)
forms the dot product of two vectors. uses unrolled loops for increments equal to one.
Author
jack dongarra, linpack, 3/11/78.
Arguments
Type Intent Optional Attributes Name
integer :: n
real(kind=wp) :: dx(*)
integer :: incx
real(kind=wp) :: dy(*)
integer :: incy
Return Value real(kind=wp)
Called By
Source Code
ddot
Source Code
    real(wp) function ddot(n,dx,incx,dy,incy)
    implicit none
    real(wp) :: dx(*) , dy(*) , dtemp
    integer :: i , incx , incy , ix , iy , m , mp1 , n
    ddot = zero
    dtemp = zero
    if ( n<=0 ) return
    if ( incx==1 .and. incy==1 ) then
        ! code for both increments equal to 1
        ! clean-up loop
        m = mod(n,5)
        if ( m/=0 ) then
            do i = 1 , m
                dtemp = dtemp + dx(i)*dy(i)
            end do
            if ( n<5 ) then
                ddot = dtemp
                return
            end if
        end if
        mp1 = m + 1
        do i = mp1 , n , 5
            dtemp = dtemp + dx(i)*dy(i) + dx(i+1)*dy(i+1) + &
                    dx(i+2)*dy(i+2) + dx(i+3)*dy(i+3) + dx(i+4)*dy(i+4)
        end do
        ddot = dtemp
    else
        ! code for unequal increments or equal increments
        ! not equal to 1
        ix = 1
        iy = 1
        if ( incx<0 ) ix = (-n+1)*incx + 1
        if ( incy<0 ) iy = (-n+1)*incy + 1
        do i = 1 , n
            dtemp = dtemp + dx(ix)*dy(iy)
            ix = ix + incx
            iy = iy + incy
        end do
        ddot = dtemp
    end if
    end function ddot
All Procedures
daxpy dcopy ddot destroy_linmin_data destroy_slsqp destroy_slsqpb_data diff dnrm2 dscal dummy_grad enforce_bounds func g1 grad h12 hfti initialize_slsqp ldl ldp linmin lsei lsi lsq mode_to_status_message nnls report_iteration report_iteration report_iteration report_iteration report_message rosenbrock_func rosenbrock_func rosenbrock_grad slsqp slsqp_wrapper slsqpb stop_iterations test_func test_grad
Call graph
ldp calls ddot
lsei calls ddot, lsi
slsqpb calls ddot, lsq
lsi calls ddot, ldp
lsq calls ddot, lsei
slsqp calls slsqpb
slsqp_wrapper calls slsqp