diff – slsqp
diff Function
7 statements
Source File
private pure elemental function diff(u, v) result(d)
Replaced statement function in the original code. Returns \(d = u - v \).
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: u
real(kind=wp), intent(in) :: v
Return Value real(kind=wp)
Called By
Source Code
diff
Source Code
    pure elemental function diff(u,v) result(d)
    implicit none
    real(wp),intent(in) :: u
    real(wp),intent(in) :: v
    real(wp)            :: d
    d = u - v
    end function diff
All Procedures
check_convergence daxpy dcopy ddot destroy_linmin_data destroy_slsqp destroy_slsqpb_data diff dnrm2 dscal dummy_grad enforce_bounds func g1 grad h12 hfti initialize_slsqp ldl ldp linmin lsei lsi lsq mode_to_status_message nnls report_iteration report_iteration report_iteration report_iteration report_iteration report_message rosenbrock_func rosenbrock_func rosenbrock_func rosenbrock_grad rosenbrock_grad slsqp slsqp_wrapper slsqpb stop_iterations test_func test_grad
Call graph
nnls calls diff
ldp calls diff, nnls
hfti calls diff
lsi calls ldp
lsei calls hfti, lsi
lsq calls lsei
slsqpb calls lsq
slsqp calls slsqpb
slsqp_wrapper calls slsqp