dnrm2 – slsqp
dnrm2 Function
29 statements
Source File
public function dnrm2(n, x, incx)
Function that returns the Euclidean norm \(\sqrt{ \mathbf{x}^T \mathbf{x} } \) of a vector \(\mathbf{x} \).
Further details
this version written on 25-october-1982.
modified on 14-october-1993 to inline the call to dlassq. sven hammarling, nag ltd.
Converted to modern Fortran, Jacob Williams, Jan. 2016.
Note
Replaced original SLSQP routine with this one from BLAS.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: n
real(kind=wp), intent(in), dimension(*) :: x
integer, intent(in) :: incx
Return Value real(kind=wp)
Called By
Source Code
dnrm2
Source Code
    real(wp) function dnrm2(n,x,incx)
    implicit none
    integer,intent(in)               :: incx
    integer,intent(in)               :: n
    real(wp),dimension(*),intent(in) :: x
    real(wp) :: absxi , norm , scale , ssq
    integer :: ix
    if ( n<1 .or. incx<1 ) then
        norm = zero
    elseif ( n==1 ) then
        norm = abs(x(1))
    else
        scale = zero
        ssq = one
        ! the following loop is equivalent to this call to the lapack
        ! auxiliary routine:
        ! call dlassq( n, x, incx, scale, ssq )
        do ix = 1 , 1 + (n-1)*incx , incx
            if ( abs(x(ix))>zero ) then
                absxi = abs(x(ix))
                if ( scale<absxi ) then
                    ssq = one + ssq*(scale/absxi)**2
                    scale = absxi
                else
                    ssq = ssq + (absxi/scale)**2
                end if
            end if
        end do
        norm = scale*sqrt(ssq)
    end if
    dnrm2 = norm
    end function dnrm2
All Procedures
check_convergence daxpy dcopy ddot destroy_linmin_data destroy_slsqp destroy_slsqpb_data diff dnrm2 dscal dummy_grad enforce_bounds func g1 grad h12 hfti initialize_slsqp ldl ldp linmin lsei lsi lsq mode_to_status_message nnls report_iteration report_iteration report_iteration report_iteration report_iteration report_message rosenbrock_func rosenbrock_func rosenbrock_func rosenbrock_grad rosenbrock_grad slsqp slsqp_wrapper slsqpb stop_iterations test_func test_grad
Call graph
check_convergence calls dnrm2
ldp calls dnrm2
lsei calls dnrm2, lsi
lsi calls dnrm2, ldp
slsqpb calls check_convergence, lsq
slsqp calls slsqpb
slsqp_wrapper calls slsqp
lsq calls lsei