dscal – slsqp
dscal Subroutine
28 statements
Source File
public subroutine dscal(n, da, dx, incx)
scales a vector by a constant. uses unrolled loops for increment equal to one.
Author
jack dongarra, linpack, 3/11/78.
Arguments
Type Intent Optional Attributes Name
integer :: n
real(kind=wp) :: da
real(kind=wp) :: dx(*)
integer :: incx
Called By
Source Code
dscal
Source Code
    subroutine dscal(n,da,dx,incx)
    implicit none
    real(wp) :: da , dx(*)
    integer :: i , incx , m , mp1 , n , nincx
    if ( n<=0 .or. incx<=0 ) return
    if ( incx==1 ) then
        ! code for increment equal to 1
        ! clean-up loop
        m = mod(n,5)
        if ( m/=0 ) then
            do i = 1 , m
                dx(i) = da*dx(i)
            end do
            if ( n<5 ) return
        end if
        mp1 = m + 1
        do i = mp1 , n , 5
            dx(i) = da*dx(i)
            dx(i+1) = da*dx(i+1)
            dx(i+2) = da*dx(i+2)
            dx(i+3) = da*dx(i+3)
            dx(i+4) = da*dx(i+4)
        end do
    else
        ! code for increment not equal to 1
        nincx = n*incx
        do i = 1 , nincx , incx
            dx(i) = da*dx(i)
        end do
    end if
    end subroutine dscal
All Procedures
daxpy dcopy ddot destroy_linmin_data destroy_slsqp destroy_slsqpb_data diff dnrm2 dscal dummy_grad enforce_bounds g1 h12 hfti initialize_slsqp ldl ldp linmin lsei lsi lsq mode_to_status_message nnls report_iteration report_iteration report_iteration report_message rosenbrock_func rosenbrock_func rosenbrock_grad slsqp slsqp_wrapper slsqpb stop_iterations test_func test_grad
Call graph
slsqpb calls dscal, lsq
lsq calls dscal
slsqp calls slsqpb
slsqp_wrapper calls slsqp