enforce_bounds – slsqp
enforce_bounds Subroutine
11 statements
Source File
private subroutine enforce_bounds(x, xl, xu)
enforce the bound constraints on x.
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(inout), dimension(:) :: x
optimization variable vector
real(kind=wp), intent(in), dimension(:) :: xl
lower bounds (must be same dimension as x)
real(kind=wp), intent(in), dimension(:) :: xu
upper bounds (must be same dimension as x)
Called By
Source Code
enforce_bounds
Source Code
    subroutine enforce_bounds(x,xl,xu)
    implicit none
    real(wp),dimension(:),intent(inout) :: x   !! optimization variable vector
    real(wp),dimension(:),intent(in)    :: xl  !! lower bounds (must be same dimension as `x`)
    real(wp),dimension(:),intent(in)    :: xu  !! upper bounds (must be same dimension as `x`)
    where (x<xl)
        x = xl
    elsewhere (x>xu)
        x = xu
    end where
    end subroutine enforce_bounds
All Procedures
check_convergence daxpy dcopy ddot destroy_linmin_data destroy_slsqp destroy_slsqpb_data diff dnrm2 dscal dummy_grad enforce_bounds func g1 grad h12 hfti initialize_slsqp ldl ldp linmin lsei lsi lsq mode_to_status_message nnls report_iteration report_iteration report_iteration report_iteration report_iteration report_message rosenbrock_func rosenbrock_func rosenbrock_func rosenbrock_grad rosenbrock_grad slsqp slsqp_wrapper slsqpb stop_iterations test_func test_grad
Call graph
slsqpb calls enforce_bounds, lsq
lsq calls enforce_bounds
slsqp calls slsqpb
slsqp_wrapper calls slsqp