g1 – slsqp
g1 Subroutine
28 statements
Source File
private subroutine g1(a, b, c, s, sig)
Compute orthogonal rotation matrix.
Compute matrix \(\left[ \begin{array}{cc} c & s \\ -s & c \end{array} \right] \) so that \(\left[ \begin{array}{cc} c & s \\ -s & c \end{array} \right] \left[ \begin{array}{c} a \\ b \end{array} \right] = \left[ \begin{array}{c} \sqrt{a^2+b^2} \\ 0 \end{array} \right] \)
Compute \(\sigma = \sqrt{a^2+b^2} \)
\(\sigma \) is computed last to allow for the possibility that sig may be in the same location as a or b.
References
C.L. Lawson, R.J. Hanson, 'Solving least squares problems' Prentice Hall, 1974. (revised 1995 edition)
lawson-hanson from Netlib.
History
Jacob Williams, refactored into modern Fortran, Jan. 2016.
Arguments
Type Intent Optional Attributes Name
real(kind=wp) :: a
real(kind=wp) :: b
real(kind=wp), intent(out) :: c
real(kind=wp), intent(out) :: s
real(kind=wp) :: sig
Called By
Source Code
g1
Source Code
    subroutine g1(a,b,c,s,sig)
    implicit none
    real(wp)             :: a
    real(wp)             :: b
    real(wp)             :: sig
    real(wp),intent(out) :: c
    real(wp),intent(out) :: s
    real(wp) :: xr, yr
    if ( abs(a)>abs(b) ) then
        xr = b/a
        yr = sqrt(one+xr**2)
        c = sign(one/yr,a)
        s = c*xr
        sig = abs(a)*yr
    else
        if ( b/=zero ) then
            xr = a/b
            yr = sqrt(one+xr**2)
            s = sign(one/yr,b)
            c = s*xr
            sig = abs(b)*yr
        else
            sig = zero
            c = zero
            s = one
        end if
    end if
    end subroutine g1
All Procedures
daxpy dcopy ddot destroy_linmin_data destroy_slsqp destroy_slsqpb_data diff dnrm2 dscal enforce_bounds g1 h12 hfti initialize_slsqp ldl ldp linmin lsei lsi lsq mode_to_status_message nnls report_iteration report_iteration report_iteration report_message rosenbrock_func rosenbrock_func rosenbrock_grad slsqp slsqp_wrapper slsqpb stop_iterations test_func test_grad
Call graph
nnls calls g1
ldp calls nnls
lsi calls ldp
lsei calls lsi
lsq calls lsei
slsqpb calls lsq
slsqp calls slsqpb
slsqp_wrapper calls slsqp