ldp – slsqp
ldp Subroutine
Source File
private subroutine ldp(g, mdg, m, n, h, x, xnorm, w, index, mode)
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(mdg,n) :: g
on entry g stores the m by n matrix of linear inequality constraints. g has first dimensioning parameter mg
integer, intent(in) :: mdg
integer, intent(in) :: m
integer, intent(in) :: n
real(kind=wp), intent(in), dimension(m) :: h
the right side of the inequality system.
real(kind=wp), intent(out), dimension(n) :: x
solution vector x if mode=1.
real(kind=wp), intent(out) :: xnorm
euclidian norm of the solution vector if computation is successful
real(kind=wp), intent(inout), dimension(*) :: w
w is a one dimensional working space, the length of which should be at least (m+2)*(n+1) + 2*m. on exit w stores the lagrange multipliers associated with the constraints. at the solution of problem ldp.
integer, intent(inout), dimension(m) :: index
integer working space
integer, intent(out) :: mode
success-failure flag with the following meanings: 1: successful computation, 2: error return because of wrong dimensions (n<=0), 3: iteration count exceeded by nnls, 4: inequality constraints incompatible.
Description
Least distance programming routine. Minimize \(\frac{1}{2} \mathbf{x}^T \mathbf{x} \) subject to \(\mathbf{G} \mathbf{x} \ge \mathbf{h} \).
The declared dimension of w() must be at least (n+1)(m+2)+2m:
   first (n+1)*m locs of w()  =  matrix e for problem nnls.
   next     n+1 locs of w()   =  vector f for problem nnls.
   next     n+1 locs of w()   =  vector z for problem nnls.
   next       m locs of w()   =  vector y for problem nnls.
   next       m locs of w()   =  vector wdual for problem nnls.
References
C.L. Lawson, R.J. Hanson, 'Solving least squares problems' Prentice Hall, 1974. (revised 1995 edition)
lawson-hanson from Netlib.
History
Jacob Williams, refactored into modern Fortran, Jan. 2016.
Calls
Called By
Variables
Type Visibility Attributes Name Initial
integer, public :: i
integer, public :: iw
integer, public :: iwdual
integer, public :: iy
integer, public :: iz
integer, public :: j
integer, public :: jf
integer, public :: np1
real(kind=wp), public :: fac
real(kind=wp), public :: rnorm
Source Code
    subroutine ldp(g,mdg,m,n,h,x,xnorm,w,index,mode)
    implicit none
    integer,intent(in)                   :: mdg
    integer,intent(in)                   :: m
    integer,intent(in)                   :: n
    real(wp),dimension(mdg,n),intent(in) :: g     !! on entry `g` stores the `m` by `n` matrix of
                                                  !! linear inequality constraints. `g` has first
                                                  !! dimensioning parameter `mg`
    real(wp),dimension(m),intent(in)     :: h     !! the right side of the inequality system.
    real(wp),dimension(n),intent(out)    :: x     !! solution vector `x` if `mode=1`.
    real(wp),dimension(*),intent(inout)  :: w     !! `w` is a one dimensional working space, the length
                                                  !! of which should be at least `(m+2)*(n+1) + 2*m`.
                                                  !! on exit `w` stores the lagrange multipliers
                                                  !! associated with the constraints.
                                                  !! at the solution of problem `ldp`.
    integer,dimension(m),intent(inout)   :: index !! integer working space
    real(wp),intent(out)                 :: xnorm !! euclidian norm of the solution vector
                                                  !! if computation is successful
    integer,intent(out)                  :: mode  !! success-failure flag with the following meanings:
                                                  !! ***1:*** successful computation,
                                                  !! ***2:*** error return because of wrong dimensions (`n<=0`),
                                                  !! ***3:*** iteration count exceeded by [[nnls]],
                                                  !! ***4:*** inequality constraints incompatible.
      integer :: i , iw , iwdual , iy , iz , j , jf , np1
      real(wp) :: fac , rnorm
      if ( n<=0 ) then
         ! error return.
         mode = 2
         return
      else
         do j = 1 , n
            x(j) = zero
         end do
         xnorm = zero
         if ( m>0 ) then
            ! copy g**t into first n rows and m columns of e.
            ! copy h**t into row n+1 of e.
            iw = 0
            do j = 1 , m
               do i = 1 , n
                  iw = iw + 1
                  w(iw) = g(j,i)
               end do
               iw = iw + 1
               w(iw) = h(j)
            end do
            jf = iw + 1
            ! store n zeros followed by a one into f.
            do i = 1 , n
               iw = iw + 1
               w(iw) = zero
            end do
            w(iw+1) = one
            np1 = n + 1
            iz = iw + 2
            iy = iz + np1
            iwdual = iy + m
            call nnls(w,np1,np1,m,w(jf),w(iy),rnorm,w(iwdual),w(iz),index,mode)
            if ( mode/=1 ) return ! if unsuccessful in nnls.
            if ( rnorm<=zero ) then
               ! returning with constraints not compatible.
               mode = 4
               return
            else
               fac = one
               iw = iy - 1
               do i = 1 , m
                  iw = iw + 1
                  ! here we are using the solution vector y.
                  fac = fac - h(i)*w(iw)
               end do
               if ( diff(one+fac,one)<=zero ) then
                  mode = 4
                  return
               else
                  fac = one/fac
                  do j = 1 , n
                     iw = iy - 1
                     do i = 1 , m
                        iw = iw + 1
                        ! here we are using the solution vector y.
                        x(j) = x(j) + g(i,j)*w(iw)
                     end do
                     x(j) = x(j)*fac
                  end do
                  do j = 1 , n
                     xnorm = xnorm + x(j)**2
                  end do
                  xnorm = sqrt(xnorm)
               end if
            end if
         end if
         ! successful return.
         mode = 1
      end if
    end subroutine ldp
Call graph
ldp calls nnls, diff
nnls calls diff, g1, h12
lsi calls ldp
lsei calls lsi
lsq calls lsei
slsqpb calls lsq
slsqp calls slsqpb
slsqp_wrapper calls slsqp