lsi – slsqp
lsi Subroutine
43 statements
Source File
private subroutine lsi(e, f, g, h, le, me, lg, mg, n, x, xnorm, w, jw, mode)
for mode=1, the subroutine returns the solution x of inequality constrained linear least squares problem:
\(\underset{x}{\min} ||E x - f|| \)
s.t. \(G x \ge h \).
the following dimensions of the arrays defining the problem are necessary:
     dim(e) :   formal (le,n),    actual (me,n)
     dim(f) :   formal (le  ),    actual (me  )
     dim(g) :   formal (lg,n),    actual (mg,n)
     dim(h) :   formal (lg  ),    actual (mg  )
     dim(x) :   n
     dim(w) :   (n+1)*(mg+2) + 2*mg
     dim(jw):   lg
on entry, the user has to provide the arrays e, f, g, and h. on return, all arrays will be changed by the subroutine.
Reference
Chapter 23.6 of Lawson & Hanson: Solving least squares problems.
History
03.01.1980, dieter kraft: coded
20.03.1987, dieter kraft: revised to fortran 77
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(inout), dimension(le,n) :: e
real(kind=wp), intent(inout), dimension(le) :: f
real(kind=wp), intent(inout), dimension(lg,n) :: g
real(kind=wp), intent(inout), dimension(lg) :: h
integer, intent(in) :: le
integer, intent(in) :: me
integer, intent(in) :: lg
integer, intent(in) :: mg
integer, intent(in) :: n
real(kind=wp), intent(out), dimension(n) :: x
stores the solution vector
real(kind=wp), intent(out) :: xnorm
stores the residuum of the solution in euclidian norm
real(kind=wp), intent(inout), dimension(*) :: w
stores the vector of lagrange multipliers in its first mg elements
integer, intent(inout), dimension(lg) :: jw
integer, intent(out) :: mode
is a success-failure flag with the following meanings:
1: successful computation,
2: error return because of wrong dimensions (n<1),
3: iteration count exceeded by nnls,
4: inequality constraints incompatible,
5: matrix e is not of full rank.
Calls
Called By
Source Code
lsi
Source Code
    subroutine lsi(e,f,g,h,le,me,lg,mg,n,x,xnorm,w,jw,mode)
    implicit none
    integer,intent(in)                      :: le
    integer,intent(in)                      :: me
    integer,intent(in)                      :: lg
    integer,intent(in)                      :: mg
    integer,intent(in)                      :: n
    real(wp),dimension(le,n),intent(inout)  :: e
    real(wp),dimension(le)  ,intent(inout)  :: f
    real(wp),dimension(lg,n),intent(inout)  :: g
    real(wp),dimension(lg)  ,intent(inout)  :: h
    real(wp),dimension(n)   ,intent(out)    :: x     !! stores the solution vector
    real(wp),intent(out)                    :: xnorm !! stores the residuum of the solution in euclidian norm
    real(wp),dimension(*)   ,intent(inout)  :: w     !! stores the vector of lagrange multipliers in its first
                                                     !! `mg` elements
    integer,dimension(lg)   ,intent(inout)  :: jw
    integer,intent(out)                     :: mode  !! is a success-failure flag with the following meanings:
                                                     !!
                                                     !! * ***1:*** successful computation,
                                                     !! * ***2:*** error return because of wrong dimensions (`n<1`),
                                                     !! * ***3:*** iteration count exceeded by [[nnls]],
                                                     !! * ***4:*** inequality constraints incompatible,
                                                     !! * ***5:*** matrix `e` is not of full rank.
    integer :: i, j
    real(wp) :: t
    !  qr-factors of e and application to f
    do i = 1 , n
        j = min(i+1,n)
        call h12(1,i,i+1,me,e(1,i),1,t,e(1,j),1,le,n-i)
        call h12(2,i,i+1,me,e(1,i),1,t,f,1,1,1)
    end do
    !  transform g and h to get least distance problem
    mode = 5
    do i = 1 , mg
        do j = 1 , n
            if ( abs(e(j,j))<epmach ) return
            g(i,j) = (g(i,j)-ddot(j-1,g(i,1),lg,e(1,j),1))/e(j,j)
        end do
        h(i) = h(i) - ddot(n,g(i,1),lg,f,1)
    end do
    !  solve least distance problem
    call ldp(g,lg,mg,n,h,x,xnorm,w,jw,mode)
    if ( mode==1 ) then
        !  solution of original problem
        call daxpy(n,one,f,1,x,1)
        do i = n , 1 , -1
            j = min(i+1,n)
            x(i) = (x(i)-ddot(n-i,e(i,j),le,x(j),1))/e(i,i)
        end do
        j = min(n+1,me)
        t = dnrm2(me-n,f(j),1)
        xnorm = sqrt(xnorm*xnorm+t*t)
    end if
    end subroutine lsi
All Procedures
daxpy dcopy ddot destroy_linmin_data destroy_slsqp destroy_slsqpb_data diff dnrm2 dscal dummy_grad enforce_bounds g1 h12 hfti initialize_slsqp ldl ldp linmin lsei lsi lsq mode_to_status_message nnls report_iteration report_iteration report_iteration report_message rosenbrock_func rosenbrock_func rosenbrock_grad slsqp slsqp_wrapper slsqpb stop_iterations test_func test_grad
Call graph
lsi calls ddot, dnrm2, daxpy, h12, ldp
ldp calls ddot, dnrm2, daxpy, nnls, dcopy, diff
nnls calls h12, diff, g1
lsei calls lsi
lsq calls lsei
slsqpb calls lsq
slsqp calls slsqpb
slsqp_wrapper calls slsqp