lsq – slsqp
lsq Subroutine
102 statements
Source File
private subroutine lsq(m, meq, n, nl, la, l, g, a, b, xl, xu, x, y, w, mode)
Minimize \(|| e x - f || \) with respect to \(x\), with upper triangular matrix \(e = + d ^{1/2} l^T \), and vector \(f = -d^{-1/2} l^{-1} g \), where the unit lower tridiangular matrix \(l\) is stored columnwise dense in the \(n*(n+1)/2\) array \(l\) with vector \(d\) stored in its 'diagonal' thus substituting the one-elements of \(l\)
subject to:
\(a(j)*x - b(j) = 0, j=1,...,meq \),
\(a(j)*x - b(j) \ge 0, j=meq+1,...,m\),
\(x_l(i) \le x(i) \le x_u(i), i=1,...,n \),
On entry, the user has to provide the arrays l, g, a, b, xl, xu. with dimensions: l(n*(n+1)/2), g(n), a(la,n), b(m), xl(n), xu(n).
The working array w must have at least the following dimension: dim(w) =
(3*n+m)*(n+1) for lsq
+(n-meq+1)*(mineq+2) + 2*mineq for lsi
+(n+mineq)*(n-meq) + 2*meq + n for lsei
with mineq = m - meq + 2*n
On return, no array will be changed by the subroutine.
History
coded dieter kraft, april 1987
revised march 1989
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: m
integer, intent(in) :: meq
integer, intent(in) :: n
integer, intent(in) :: nl
integer, intent(in) :: la
real(kind=wp), dimension(nl) :: l
real(kind=wp), dimension(n) :: g
real(kind=wp), dimension(la,n) :: a
real(kind=wp), dimension(la) :: b
real(kind=wp), dimension(n) :: xl
real(kind=wp), dimension(n) :: xu
real(kind=wp), dimension(n) :: x
stores the n-dimensional solution vector
real(kind=wp), dimension(m+n+n) :: y
stores the vector of lagrange multipliers of dimension m+n+n (constraints+lower+upper bounds)
real(kind=wp), dimension(*) :: w
integer :: mode
is a success-failure flag with the following meanings:
1: successful computation,
2: error return because of wrong dimensions (n<1),
3: iteration count exceeded by nnls,
4: inequality constraints incompatible,
5: matrix e is not of full rank,
6: matrix c is not of full rank,
7: rank defect in hfti
Calls
Called By
Source Code
lsq
Source Code
    subroutine lsq(m,meq,n,nl,la,l,g,a,b,xl,xu,x,y,w,mode)
    implicit none
    integer,intent(in)        :: m
    integer,intent(in)        :: n
    integer,intent(in)        :: meq
    integer,intent(in)        :: nl
    integer,intent(in)        :: la
    real(wp),dimension(n)     :: x  !! stores the n-dimensional solution vector
    real(wp),dimension(m+n+n) :: y  !! stores the vector of lagrange multipliers of dimension
                                    !! m+n+n (constraints+lower+upper bounds)
    integer :: mode                 !! is a success-failure flag with the following meanings:
                                    !!
                                    !! * **1:** successful computation,
                                    !! * **2:** error return because of wrong dimensions (`n<1`),
                                    !! * **3:** iteration count exceeded by [[nnls]],
                                    !! * **4:** inequality constraints incompatible,
                                    !! * **5:** matrix `e` is not of full rank,
                                    !! * **6:** matrix `c` is not of full rank,
                                    !! * **7:** rank defect in [[hfti]]
    real(wp),dimension(nl)   :: l
    real(wp),dimension(n)    :: g
    real(wp),dimension(la,n) :: a
    real(wp),dimension(la)   :: b
    real(wp),dimension(*)    :: w
    real(wp),dimension(n)    :: xl
    real(wp),dimension(n)    :: xu
    real(wp) :: diag , xnorm
    integer :: i , ic , id , ie , if , ig , ih , il , im , ip , &
               iu , iw , i1 , i2 , i3 , i4 , mineq , &
               m1 , n1 , n2 , n3
      n1 = n + 1
      mineq = m - meq
      m1 = mineq + n + n
      !  determine whether to solve problem
      !  with inconsistent linerarization (n2=1)
      !  or not (n2=0)
      n2 = n1*n/2 + 1
      if ( n2==nl ) then
         n2 = 0
      else
         n2 = 1
      end if
      n3 = n - n2
      !  recover matrix e and vector f from l and g
      i2 = 1
      i3 = 1
      i4 = 1
      ie = 1
      if = n*n + 1
      do i = 1 , n3
         i1 = n1 - i
         diag = sqrt(l(i2))
         w(i3) = zero
         call dcopy(i1,w(i3),0,w(i3),1)
         call dcopy(i1-n2,l(i2),1,w(i3),n)
         call dscal(i1-n2,diag,w(i3),n)
         w(i3) = diag
         w(if-1+i) = (g(i)-ddot(i-1,w(i4),1,w(if),1))/diag
         i2 = i2 + i1 - n2
         i3 = i3 + n1
         i4 = i4 + n
      end do
      if ( n2==1 ) then
         w(i3) = l(nl)
         w(i4) = zero
         call dcopy(n3,w(i4),0,w(i4),1)
         w(if-1+n) = zero
      end if
      call dscal(n,-one,w(if),1)
      ic = if + n
      id = ic + meq*n
      if ( meq>0 ) then
         !  recover matrix c from upper part of a
         do i = 1 , meq
            call dcopy(n,a(i,1),la,w(ic-1+i),meq)
         end do
         !  recover vector d from upper part of b
         call dcopy(meq,b(1),1,w(id),1)
         call dscal(meq,-one,w(id),1)
      end if
      ig = id + meq
      if ( mineq>0 ) then
         !  recover matrix g from lower part of a
         do i = 1 , mineq
            call dcopy(n,a(meq+i,1),la,w(ig-1+i),m1)
         end do
      end if
      !  augment matrix g by +i and -i
      ip = ig + mineq
      do i = 1 , n
         w(ip-1+i) = zero
         call dcopy(n,w(ip-1+i),0,w(ip-1+i),m1)
      end do
      w(ip) = one
      call dcopy(n,w(ip),0,w(ip),m1+1)
      im = ip + n
      do i = 1 , n
         w(im-1+i) = zero
         call dcopy(n,w(im-1+i),0,w(im-1+i),m1)
      end do
      w(im) = -one
      call dcopy(n,w(im),0,w(im),m1+1)
      ih = ig + m1*n
      if ( mineq>0 ) then
         ! recover h from lower part of b
         call dcopy(mineq,b(meq+1),1,w(ih),1)
         call dscal(mineq,-one,w(ih),1)
      end if
      !  augment vector h by xl and xu
      il = ih + mineq
      call dcopy(n,xl,1,w(il),1)
      iu = il + n
      call dcopy(n,xu,1,w(iu),1)
      call dscal(n,-one,w(iu),1)
      iw = iu + n
      call lsei(w(ic),w(id),w(ie),w(if),w(ig),w(ih),max(1,meq),meq,n,n, &
                m1,m1,n,x,xnorm,w(iw),mode)
      if ( mode==1 ) then
         ! restore lagrange multipliers
         call dcopy(m,w(iw),1,y(1),1)
         call dcopy(n3,w(iw+m),1,y(m+1),1)
         call dcopy(n3,w(iw+m+n),1,y(m+n3+1),1)
         call enforce_bounds(x,xl,xu)  ! to ensure that bounds are not violated
      end if
      end subroutine lsq
All Procedures
check_convergence daxpy dcopy ddot destroy_linmin_data destroy_slsqp destroy_slsqpb_data diff dnrm2 dscal dummy_grad enforce_bounds func g1 grad h12 hfti initialize_slsqp ldl ldp linmin lsei lsi lsq mode_to_status_message nnls report_iteration report_iteration report_iteration report_iteration report_iteration report_message rosenbrock_func rosenbrock_func rosenbrock_func rosenbrock_grad rosenbrock_grad slsqp slsqp_wrapper slsqpb stop_iterations test_func test_grad
Call graph
lsq calls dcopy, enforce_bounds, ddot, lsei, dscal
lsei calls dcopy, ddot, dnrm2, hfti, h12, lsi
hfti calls h12, diff
lsi calls ddot, dnrm2, h12, daxpy, ldp
ldp calls dcopy, ddot, dnrm2, diff, daxpy, nnls
nnls calls h12, diff, g1
slsqpb calls lsq
slsqp calls slsqpb
slsqp_wrapper calls slsqp