slsqp – slsqp
slsqp Subroutine
47 statements
Source File
public subroutine slsqp(m, meq, la, n, x, xl, xu, f, c, g, a, acc, iter, mode, w, l_w, jw, l_jw, sdat, ldat, alphamin, alphamax)
slsqp: sequential least squares programming to solve general nonlinear optimization problems
a nonlinear programming method with quadratic programming subproblems this subroutine solves the general nonlinear programming problem:
minimize
\(f(x) \)
subject to
\(c_j (x) = 0 \), \(j = 1,...,meq \)
\(c_j (x) \ge 0 \), \(j = meq+1,...,m \)
\(xl_i \le x_i \le xu_i \), \(i = 1,...,n \)
the algorithm implements the method of Han and Powell with BFGS-update of the b-matrix and L1-test function within the steplength algorithm.
Reference
Dieter Kraft: "A software package for sequential quadratic programming", DFVLR-FB 88-28, 1988
History
implemented by: Dieter Kraft, DFVLR oberpfaffenhofen
date: april - october, 1981.
December, 31-st, 1984.
March , 21-st, 1987, revised to fortran 77
March , 20-th, 1989, revised to ms-fortran
April , 14-th, 1989, hesse in-line coded
February, 28-th, 1991, fortran/2 version 1.04 accepts statement functions
March , 1-st, 1991, tested with salford ftn77/386 compiler vers 2.40 in protected mode
January , 2016, Refactored into modern Fortran by Jacob Williams
License
Original version copyright 1991: Dieter Kraft, FHM. Released under a BSD license.
Note
f, c, g, a must all be set by the user before each call.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: m
is the total number of constraints, \(m \ge 0 \)
integer, intent(in) :: meq
is the number of equality constraints, \(m_{eq} \ge 0 \)
integer, intent(in) :: la
see a, \(la \ge \max(m,1) \)
integer, intent(in) :: n
is the number of variables, \(n \ge 1 \)
real(kind=wp), intent(inout), dimension(n) :: x
x() stores the current iterate of the n vector x on entry x() must be initialized. on exit x() stores the solution vector x if mode = 0.
real(kind=wp), intent(in), dimension(n) :: xl
xl() stores an n vector of lower bounds xl to x.
real(kind=wp), intent(in), dimension(n) :: xu
xu() stores an n vector of upper bounds xu to x.
real(kind=wp), intent(in) :: f
is the value of the objective function.
real(kind=wp), intent(in), dimension(la) :: c
c() stores the m vector c of constraints, equality constraints (if any) first. dimension of c must be greater or equal la, which must be greater or equal max(1,m).
real(kind=wp), intent(in), dimension(n+1) :: g
g() stores the n vector g of partials of the objective function; dimension of g must be greater or equal n+1.
real(kind=wp), intent(in), dimension(la,n+1) :: a
the la by n + 1 array a() stores the m by n matrix a of constraint normals. a() has first dimensioning parameter la, which must be greater or equal max(1,m).
real(kind=wp), intent(inout) :: acc
abs(acc) controls the final accuracy. if acc < zero an exact linesearch is performed, otherwise an armijo-type linesearch is used.
integer, intent(inout) :: iter
prescribes the maximum number of iterations. on exit iter indicates the number of iterations.
integer, intent(inout) :: mode
mode controls calculation:
reverse communication is used in the sense that the program is initialized by mode = 0; then it is to be called repeatedly by the user until a return with mode /= abs(1) takes place. if mode = -1 gradients have to be calculated, while with mode = 1 functions have to be calculated. mode must not be changed between subsequent calls of slsqp.
evaluation modes:
-1 : gradient evaluation, (g & a)
0 : on entry: initialization, (f, g, c, a), on exit: required accuracy for solution obtained
1 : function evaluation, (f & c)
failure modes:
2 : number of equality constraints larger than n
3 : more than 3*n iterations in lsq subproblem
4 : inequality constraints incompatible
5 : singular matrix e in lsq subproblem
6 : singular matrix c in lsq subproblem
7 : rank-deficient equality constraint subproblem hfti
8 : positive directional derivative for linesearch
9 : more than iter iterations in sqp
>=10 : working space w or jw too small, w should be enlarged to l_w=mode/1000, jw should be enlarged to l_jw=mode-1000*l_w
real(kind=wp), intent(inout), dimension(l_w) :: w
w() is a one dimensional working space. the first m+n+n*n1/2 elements of w must not be changed between subsequent calls of slsqp. on return w(1) ... w(m) contain the multipliers associated with the general constraints, while w(m+1) ... w(m+n(n+1)/2) store the cholesky factor l*d*l(t) of the approximate hessian of the lagrangian columnwise dense as lower triangular unit matrix l with d in its 'diagonal' and w(m+n(n+1)/2+n+2 ... w(m+n(n+1)/2+n+2+m+2n) contain the multipliers associated with all constraints of the quadratic program finding the search direction to the solution x*
integer, intent(in) :: l_w
the length of w, which should be at least:
(3*n1+m)*(n1+1) for lsq
+(n1-meq+1)*(mineq+2) + 2*mineq for lsi
+(n1+mineq)*(n1-meq) + 2*meq + n1 for lsei
+ n1*n/2 + 2*m + 3*n + 3*n1 + 1 for slsqpb
with mineq = m - meq + 2*n1 & n1 = n+1
integer, intent(inout), dimension(l_jw) :: jw
jw() is a one dimensional integer working space
integer, intent(in) :: l_jw
the length of jw which should be at least mineq = m - meq + 2*(n+1).
type(slsqpb_data), intent(inout) :: sdat
data for slsqpb.
type(linmin_data), intent(inout) :: ldat
data for linmin.
real(kind=wp), intent(in) :: alphamin
min \(\alpha \) for line search \(0 < \alpha_{min} < \alpha_{max} \le 1 \)
real(kind=wp), intent(in) :: alphamax
max \(\alpha \) for line search \(0 < \alpha_{min} < \alpha_{max} \le 1 \)
Calls
Called By
Source Code
slsqp
Source Code
    subroutine slsqp(m,meq,la,n,x,xl,xu,f,c,g,a,acc,iter,mode,w,l_w, &
                     jw,l_jw,sdat,ldat,alphamin,alphamax)
    implicit none
    integer,intent(in) :: m                     !! is the total number of constraints, \( m \ge 0 \)
    integer,intent(in) :: meq                   !! is the number of equality constraints, \( m_{eq} \ge 0 \)
    integer,intent(in) :: la                    !! see `a`, \( la \ge \max(m,1) \)
    integer,intent(in) :: n                     !! is the number of variables, \( n \ge 1 \)
    real(wp),dimension(n),intent(inout) :: x    !! `x()` stores the current iterate of the `n` vector `x`
                                                !! on entry `x()` must be initialized. on exit `x()`
                                                !! stores the solution vector `x` if `mode = 0`.
    real(wp),dimension(n),intent(in) :: xl      !! `xl()` stores an n vector of lower bounds `xl` to `x`.
    real(wp),dimension(n),intent(in) :: xu      !! `xu()` stores an n vector of upper bounds `xu` to `x`.
    real(wp),intent(in) :: f                    !! is the value of the objective function.
    real(wp),dimension(la),intent(in) :: c      !! `c()` stores the `m` vector `c` of constraints,
                                                !! equality constraints (if any) first.
                                                !! dimension of `c` must be greater or equal `la`,
                                                !! which must be greater or equal `max(1,m)`.
    real(wp),dimension(n+1),intent(in) :: g     !! `g()` stores the `n` vector `g` of partials of the
                                                !! objective function; dimension of `g` must be
                                                !! greater or equal `n+1`.
    real(wp),dimension(la,n+1),intent(in) ::  a !! the `la` by `n + 1` array `a()` stores
                                                !! the `m` by `n` matrix `a` of constraint normals.
                                                !! `a()` has first dimensioning parameter `la`,
                                                !! which must be greater or equal `max(1,m)`.
    real(wp),intent(inout) :: acc   !! `abs(acc)` controls the final accuracy.
                                    !! if `acc` < zero an exact linesearch is performed,
                                    !! otherwise an armijo-type linesearch is used.
    integer,intent(inout) :: iter   !! prescribes the maximum number of iterations.
                                    !! on exit `iter` indicates the number of iterations.
    integer,intent(inout) :: mode   !! mode controls calculation:
                                    !!
                                    !! reverse communication is used in the sense that
                                    !! the program is initialized by `mode = 0`; then it is
                                    !! to be called repeatedly by the user until a return
                                    !! with `mode /= abs(1)` takes place.
                                    !! if `mode = -1` gradients have to be calculated,
                                    !! while with `mode = 1` functions have to be calculated.
                                    !! mode must not be changed between subsequent calls of [[slsqp]].
                                    !!
                                    !! **evaluation modes**:
                                    !!
                                    !! * ** -1 **: gradient evaluation, (`g` & `a`)
                                    !! * **  0 **: *on entry*: initialization, (`f`, `g`, `c`, `a`),
                                    !!   *on exit*: required accuracy for solution obtained
                                    !! * **  1 **: function evaluation, (`f` & `c`)
                                    !!
                                    !! **failure modes**:
                                    !!
                                    !! * ** 2 **: number of equality constraints larger than `n`
                                    !! * ** 3 **: more than `3*n` iterations in [[lsq]] subproblem
                                    !! * ** 4 **: inequality constraints incompatible
                                    !! * ** 5 **: singular matrix `e` in [[lsq]] subproblem
                                    !! * ** 6 **: singular matrix `c` in [[lsq]] subproblem
                                    !! * ** 7 **: rank-deficient equality constraint subproblem [[hfti]]
                                    !! * ** 8 **: positive directional derivative for linesearch
                                    !! * ** 9 **: more than `iter` iterations in sqp
                                    !! * ** >=10 **: working space `w` or `jw` too small,
                                    !!   `w` should be enlarged to `l_w=mode/1000`,
                                    !!   `jw` should be enlarged to `l_jw=mode-1000*l_w`
    integer,intent(in) :: l_w       !! the length of `w`, which should be at least:
                                    !!
                                    !! * `(3*n1+m)*(n1+1)`                     **for lsq**
                                    !! * `+(n1-meq+1)*(mineq+2) + 2*mineq`     **for lsi**
                                    !! * `+(n1+mineq)*(n1-meq) + 2*meq + n1`   **for lsei**
                                    !! * `+ n1*n/2 + 2*m + 3*n + 3*n1 + 1`     **for slsqpb**
                                    !!
                                    !! with `mineq = m - meq + 2*n1` & `n1 = n+1`
    integer,intent(in) :: l_jw      !! the length of `jw` which should be at least
                                    !! `mineq = m - meq + 2*(n+1)`.
    real(wp),dimension(l_w),intent(inout) :: w  !! `w()` is a one dimensional working space.
                                                !! the first `m+n+n*n1/2` elements of `w` must not be
                                                !! changed between subsequent calls of [[slsqp]].
                                                !! on return `w(1) ... w(m)` contain the multipliers
                                                !! associated with the general constraints, while
                                                !! `w(m+1) ... w(m+n(n+1)/2)` store the cholesky factor
                                                !! `l*d*l(t)` of the approximate hessian of the
                                                !! lagrangian columnwise dense as lower triangular
                                                !! unit matrix `l` with `d` in its 'diagonal' and
                                                !! `w(m+n(n+1)/2+n+2 ... w(m+n(n+1)/2+n+2+m+2n)`
                                                !! contain the multipliers associated with all
                                                !! constraints of the quadratic program finding
                                                !! the search direction to the solution `x*`
    integer,dimension(l_jw),intent(inout) :: jw !! `jw()` is a one dimensional integer working space
    type(slsqpb_data),intent(inout) :: sdat  !! data for [[slsqpb]].
    type(linmin_data),intent(inout) :: ldat  !! data for [[linmin]].
    real(wp),intent(in) :: alphamin  !! min \( \alpha \) for line search \( 0 < \alpha_{min} < \alpha_{max} \le 1 \)
    real(wp),intent(in) :: alphamax  !! max \( \alpha \) for line search \( 0 < \alpha_{min} < \alpha_{max} \le 1 \)
    integer :: il , im , ir , is , iu , iv , iw , ix , mineq, n1
    !  Note: there seems to be two slightly different specifications
    !        of the appropriate length of w. are they equivalent???
    !
    !         notice:    for proper dimensioning of w it is recommended to
    !                    copy the following statements into the head of
    !                    the calling program (and remove the comment c)
    ! #######################################################################
    !     integer len_w, len_jw, m, n, n1, meq, mineq
    !     parameter (m=... , meq=... , n=...  )
    !     parameter (n1= n+1, mineq= m-meq+n1+n1)
    !     parameter (len_w=
    !    $           (3*n1+m)*(n1+1)
    !    $          +(n1-meq+1)*(mineq+2) + 2*mineq
    !    $          +(n1+mineq)*(n1-meq) + 2*meq + n1
    !    $          +(n+1)*n/2 + 2*m + 3*n + 3*n1 + 1,
    !    $           len_jw=mineq)
    !     real(wp) w(len_w)
    !     integer          jw(len_jw)
    ! #######################################################################
    !
    !     dim(w) =         n1*(n1+1) + meq*(n1+1) + mineq*(n1+1)  for lsq
    !                    +(n1-meq+1)*(mineq+2) + 2*mineq          for lsi
    !                    +(n1+mineq)*(n1-meq) + 2*meq + n1        for lsei
    !                    + n1*n/2 + 2*m + 3*n +3*n1 + 1           for slsqpb
    !                      with mineq = m - meq + 2*n1  &  n1 = n+1
    !   check length of working arrays
    n1 = n + 1
    mineq = m - meq + n1 + n1
    il = (3*n1+m)*(n1+1) + (n1-meq+1)*(mineq+2) + 2*mineq + (n1+mineq)&
         *(n1-meq) + 2*meq + n1*n/2 + 2*m + 3*n + 4*n1 + 1
    im = max(mineq,n1-meq)
    if ( l_w<il .or. l_jw<im ) then
        mode = 1000*max(10,il)
        mode = mode + max(10,im)
        return
    end if
    !   prepare data for calling sqpbdy  -  initial addresses in w
    im = 1
    il = im + max(1,m)
    il = im + la
    ix = il + n1*n/2 + 1
    ir = ix + n
    is = ir + n + n + max(1,m)
    is = ir + n + n + la
    iu = is + n1
    iv = iu + n1
    iw = iv + n1
    sdat%n1 = n1
    call slsqpb(m,meq,la,n,x,xl,xu,f,c,g,a,acc,iter,mode,&
                w(ir),w(il),w(ix),w(im),w(is),w(iu),w(iv),w(iw),jw,&
                sdat%t,sdat%f0,sdat%h1,sdat%h2,sdat%h3,sdat%h4,&
                sdat%n1,sdat%n2,sdat%n3,sdat%t0,sdat%gs,sdat%tol,sdat%line,&
                sdat%alpha,sdat%iexact,sdat%incons,sdat%ireset,sdat%itermx,&
                ldat,alphamin,alphamax)
    end subroutine slsqp
All Procedures
daxpy dcopy ddot destroy_linmin_data destroy_slsqp destroy_slsqpb_data diff dnrm2 dscal enforce_bounds g1 h12 hfti initialize_slsqp ldl ldp linmin lsei lsi lsq mode_to_status_message nnls report_iteration report_iteration report_message rosenbrock_func rosenbrock_grad slsqp slsqp_wrapper slsqpb stop_iterations test_func test_grad
Call graph
slsqp calls slsqpb
slsqpb calls linmin, lsq, dnrm2, ldl, daxpy, ddot, enforce_bounds, dscal, dcopy
lsq calls ddot, enforce_bounds, dscal, dcopy, lsei
lsei calls dnrm2, ddot, dcopy, h12, lsi, hfti
lsi calls dnrm2, daxpy, ddot, h12, ldp
hfti calls h12, diff
ldp calls dnrm2, daxpy, ddot, dcopy, diff, nnls
nnls calls h12, diff, g1
slsqp_wrapper calls slsqp